export const GALLERY: Array<{
  src: string;
  alt: string;
  title: string;
  caption: string;
  category: "Kitchen" | "Bath" | "Outdoor" | "Interior" | "Custom";
}> = [
  {
    src: "/images/gallery-23-a.webp",
    alt: "Kitchen before the remodel",
    title: "Kitchen remodel",
    caption: "Before",
    category: "Kitchen",
  },
  {
    src: "/images/gallery-23-b.webp",
    alt: "Kitchen tear-out during the remodel",
    title: "Kitchen remodel",
    caption: "Tear-out",
    category: "Kitchen",
  },
  {
    src: "/images/gallery-23-c.webp",
    alt: "Cabinets going in during the remodel",
    title: "Kitchen remodel",
    caption: "Cabinets in",
    category: "Kitchen",
  },
  {
    src: "/images/gallery-23-d.webp",
    alt: "Kitchen after the remodel, sink run",
    title: "Kitchen remodel",
    caption: "After",
    category: "Kitchen",
  },
  {
    src: "/images/gallery-23-e.webp",
    alt: "Kitchen after the remodel, peninsula",
    title: "Kitchen remodel",
    caption: "After",
    category: "Kitchen",
  },
  {
    src: "/images/gallery-01-a.webp",
    alt: "Farmhouse kitchen by The Flip Fixer",
    title: "Farmhouse kitchen",
    caption: "Farmhouse kitchen",
    category: "Kitchen",
  },
  {
    src: "/images/gallery-01-b.webp",
    alt: "Farmhouse kitchen by The Flip Fixer",
    title: "Farmhouse kitchen",
    caption: "Farmhouse kitchen",
    category: "Kitchen",
  },
  {
    src: "/images/gallery-01-c.webp",
    alt: "Farmhouse kitchen by The Flip Fixer",
    title: "Farmhouse kitchen",
    caption: "Farmhouse kitchen",
    category: "Kitchen",
  },
  {
    src: "/images/gallery-02-a.webp",
    alt: "Navy island kitchen by The Flip Fixer",
    title: "Navy island kitchen",
    caption: "Navy island kitchen",
    category: "Kitchen",
  },
  {
    src: "/images/gallery-02-b.webp",
    alt: "Navy island kitchen by The Flip Fixer",
    title: "Navy island kitchen",
    caption: "Navy island kitchen",
    category: "Kitchen",
  },
  {
    src: "/images/gallery-02-c.webp",
    alt: "Navy island kitchen by The Flip Fixer",
    title: "Navy island kitchen",
    caption: "Navy island kitchen",
    category: "Kitchen",
  },
  {
    src: "/images/gallery-03-a.webp",
    alt: "Charcoal kitchen by The Flip Fixer",
    title: "Charcoal kitchen",
    caption: "Charcoal kitchen",
    category: "Kitchen",
  },
  {
    src: "/images/gallery-03-b.webp",
    alt: "Charcoal kitchen by The Flip Fixer",
    title: "Charcoal kitchen",
    caption: "Charcoal kitchen",
    category: "Kitchen",
  },
  {
    src: "/images/gallery-03-c.webp",
    alt: "Charcoal kitchen by The Flip Fixer",
    title: "Charcoal kitchen",
    caption: "Charcoal kitchen",
    category: "Kitchen",
  },
  {
    src: "/images/gallery-05-a.webp",
    alt: "Two-tone kitchen by The Flip Fixer",
    title: "Two-tone kitchen",
    caption: "Two-tone kitchen",
    category: "Kitchen",
  },
  {
    src: "/images/gallery-05-b.webp",
    alt: "Two-tone kitchen by The Flip Fixer",
    title: "Two-tone kitchen",
    caption: "Two-tone kitchen",
    category: "Kitchen",
  },
  {
    src: "/images/gallery-05-c.webp",
    alt: "Two-tone kitchen by The Flip Fixer",
    title: "Two-tone kitchen",
    caption: "Two-tone kitchen",
    category: "Kitchen",
  },
  {
    src: "/images/gallery-06-a.webp",
    alt: "Open kitchen by The Flip Fixer",
    title: "Open kitchen",
    caption: "Open kitchen",
    category: "Kitchen",
  },
  {
    src: "/images/gallery-06-b.webp",
    alt: "Open kitchen by The Flip Fixer",
    title: "Open kitchen",
    caption: "Open kitchen",
    category: "Kitchen",
  },
  {
    src: "/images/gallery-06-c.webp",
    alt: "Open kitchen living area by The Flip Fixer",
    title: "Open kitchen",
    caption: "Open kitchen",
    category: "Kitchen",
  },
  {
    src: "/images/gallery-10-a.webp",
    alt: "Dark wood kitchen by The Flip Fixer",
    title: "Dark wood kitchen",
    caption: "Dark wood kitchen",
    category: "Kitchen",
  },
  {
    src: "/images/gallery-10-b.webp",
    alt: "Dark wood kitchen by The Flip Fixer",
    title: "Dark wood kitchen",
    caption: "Dark wood kitchen",
    category: "Kitchen",
  },
  {
    src: "/images/gallery-08-a.webp",
    alt: "Gray shaker kitchen by The Flip Fixer",
    title: "Gray shaker kitchen",
    caption: "Gray shaker kitchen",
    category: "Kitchen",
  },
  {
    src: "/images/gallery-08-b.webp",
    alt: "Gray shaker kitchen by The Flip Fixer",
    title: "Gray shaker kitchen",
    caption: "Gray shaker kitchen",
    category: "Kitchen",
  },
  {
    src: "/images/gallery-08-c.webp",
    alt: "Gray shaker kitchen by The Flip Fixer",
    title: "Gray shaker kitchen",
    caption: "Gray shaker kitchen",
    category: "Kitchen",
  },
  {
    src: "/images/gallery-09-a.webp",
    alt: "White kitchen, black island by The Flip Fixer",
    title: "White kitchen, black island",
    caption: "White kitchen, black island",
    category: "Kitchen",
  },
  {
    src: "/images/gallery-09-b.webp",
    alt: "White kitchen, black island by The Flip Fixer",
    title: "White kitchen, black island",
    caption: "White kitchen, black island",
    category: "Kitchen",
  },
  {
    src: "/images/gallery-09-c.webp",
    alt: "White kitchen, black island by The Flip Fixer",
    title: "White kitchen, black island",
    caption: "White kitchen, black island",
    category: "Kitchen",
  },
  {
    src: "/images/gallery-13-a.webp",
    alt: "Granite breakfast bar by The Flip Fixer",
    title: "Granite breakfast bar",
    caption: "Granite breakfast bar",
    category: "Kitchen",
  },
  {
    src: "/images/gallery-14-a.webp",
    alt: "Cream kitchen by The Flip Fixer",
    title: "Cream kitchen",
    caption: "Cream kitchen",
    category: "Kitchen",
  },
  {
    src: "/images/gallery-15-a.webp",
    alt: "Navy island by The Flip Fixer",
    title: "Navy island",
    caption: "Navy island",
    category: "Kitchen",
  },
  {
    src: "/images/gallery-16-a.webp",
    alt: "Charcoal island by The Flip Fixer",
    title: "Charcoal island",
    caption: "Charcoal island",
    category: "Kitchen",
  },
  {
    src: "/images/gallery-17-a.webp",
    alt: "Navy island with gold accents by The Flip Fixer",
    title: "Navy gold kitchen",
    caption: "Navy gold kitchen",
    category: "Kitchen",
  },
  {
    src: "/images/gallery-18-a.webp",
    alt: "Gray and white kitchen by The Flip Fixer",
    title: "Gray and white kitchen",
    caption: "Gray and white kitchen",
    category: "Kitchen",
  },
  {
    src: "/images/gallery-18-b.webp",
    alt: "Gray and white kitchen by The Flip Fixer",
    title: "Gray and white kitchen",
    caption: "Gray and white kitchen",
    category: "Kitchen",
  },
];
