/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as CommunityRouteImport } from './routes/community'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as EstimatorRouteImport } from './routes/estimator'
import { Route as GalleryRouteImport } from './routes/gallery'
import { Route as KitchenRouteImport } from './routes/kitchen'
import { Route as LoginRouteImport } from './routes/login'
import { Route as RoofRouteImport } from './routes/roof'
import { Route as ServicesRouteImport } from './routes/services'
import { Route as TestimonialsRouteImport } from './routes/testimonials'
import { Route as EstimatorIndexRouteImport } from './routes/estimator.index'
import { Route as EstimatorRoofRouteImport } from './routes/estimator.roof'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const CommunityRoute = CommunityRouteImport.update({
  id: '/community',
  path: '/community',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const EstimatorRoute = EstimatorRouteImport.update({
  id: '/estimator',
  path: '/estimator',
  getParentRoute: () => rootRouteImport,
} as any)
const GalleryRoute = GalleryRouteImport.update({
  id: '/gallery',
  path: '/gallery',
  getParentRoute: () => rootRouteImport,
} as any)
const KitchenRoute = KitchenRouteImport.update({
  id: '/kitchen',
  path: '/kitchen',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const RoofRoute = RoofRouteImport.update({
  id: '/roof',
  path: '/roof',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesRoute = ServicesRouteImport.update({
  id: '/services',
  path: '/services',
  getParentRoute: () => rootRouteImport,
} as any)
const TestimonialsRoute = TestimonialsRouteImport.update({
  id: '/testimonials',
  path: '/testimonials',
  getParentRoute: () => rootRouteImport,
} as any)
const EstimatorIndexRoute = EstimatorIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => EstimatorRoute,
} as any)
const EstimatorRoofRoute = EstimatorRoofRouteImport.update({
  id: '/roof',
  path: '/roof',
  getParentRoute: () => EstimatorRoute,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/community': typeof CommunityRoute
  '/contact': typeof ContactRoute
  '/estimator': typeof EstimatorRouteWithChildren
  '/gallery': typeof GalleryRoute
  '/kitchen': typeof KitchenRoute
  '/login': typeof LoginRoute
  '/roof': typeof RoofRoute
  '/services': typeof ServicesRoute
  '/testimonials': typeof TestimonialsRoute
  '/estimator/roof': typeof EstimatorRoofRoute
  '/estimator/': typeof EstimatorIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/community': typeof CommunityRoute
  '/contact': typeof ContactRoute
  '/gallery': typeof GalleryRoute
  '/kitchen': typeof KitchenRoute
  '/login': typeof LoginRoute
  '/roof': typeof RoofRoute
  '/services': typeof ServicesRoute
  '/testimonials': typeof TestimonialsRoute
  '/estimator/roof': typeof EstimatorRoofRoute
  '/estimator': typeof EstimatorIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/community': typeof CommunityRoute
  '/contact': typeof ContactRoute
  '/estimator': typeof EstimatorRouteWithChildren
  '/gallery': typeof GalleryRoute
  '/kitchen': typeof KitchenRoute
  '/login': typeof LoginRoute
  '/roof': typeof RoofRoute
  '/services': typeof ServicesRoute
  '/testimonials': typeof TestimonialsRoute
  '/estimator/roof': typeof EstimatorRoofRoute
  '/estimator/': typeof EstimatorIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/community'
    | '/contact'
    | '/estimator'
    | '/gallery'
    | '/kitchen'
    | '/login'
    | '/roof'
    | '/services'
    | '/testimonials'
    | '/estimator/roof'
    | '/estimator/'
    | '/api/auth/$'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/community'
    | '/contact'
    | '/gallery'
    | '/kitchen'
    | '/login'
    | '/roof'
    | '/services'
    | '/testimonials'
    | '/estimator/roof'
    | '/estimator'
    | '/api/auth/$'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/community'
    | '/contact'
    | '/estimator'
    | '/gallery'
    | '/kitchen'
    | '/login'
    | '/roof'
    | '/services'
    | '/testimonials'
    | '/estimator/roof'
    | '/estimator/'
    | '/api/auth/$'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  CommunityRoute: typeof CommunityRoute
  ContactRoute: typeof ContactRoute
  EstimatorRoute: typeof EstimatorRouteWithChildren
  GalleryRoute: typeof GalleryRoute
  KitchenRoute: typeof KitchenRoute
  LoginRoute: typeof LoginRoute
  RoofRoute: typeof RoofRoute
  ServicesRoute: typeof ServicesRoute
  TestimonialsRoute: typeof TestimonialsRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/community': {
      id: '/community'
      path: '/community'
      fullPath: '/community'
      preLoaderRoute: typeof CommunityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/estimator': {
      id: '/estimator'
      path: '/estimator'
      fullPath: '/estimator'
      preLoaderRoute: typeof EstimatorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gallery': {
      id: '/gallery'
      path: '/gallery'
      fullPath: '/gallery'
      preLoaderRoute: typeof GalleryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kitchen': {
      id: '/kitchen'
      path: '/kitchen'
      fullPath: '/kitchen'
      preLoaderRoute: typeof KitchenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/roof': {
      id: '/roof'
      path: '/roof'
      fullPath: '/roof'
      preLoaderRoute: typeof RoofRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services': {
      id: '/services'
      path: '/services'
      fullPath: '/services'
      preLoaderRoute: typeof ServicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/testimonials': {
      id: '/testimonials'
      path: '/testimonials'
      fullPath: '/testimonials'
      preLoaderRoute: typeof TestimonialsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/estimator/': {
      id: '/estimator/'
      path: '/'
      fullPath: '/estimator/'
      preLoaderRoute: typeof EstimatorIndexRouteImport
      parentRoute: typeof EstimatorRoute
    }
    '/estimator/roof': {
      id: '/estimator/roof'
      path: '/roof'
      fullPath: '/estimator/roof'
      preLoaderRoute: typeof EstimatorRoofRouteImport
      parentRoute: typeof EstimatorRoute
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface EstimatorRouteChildren {
  EstimatorRoofRoute: typeof EstimatorRoofRoute
  EstimatorIndexRoute: typeof EstimatorIndexRoute
}

const EstimatorRouteChildren: EstimatorRouteChildren = {
  EstimatorRoofRoute: EstimatorRoofRoute,
  EstimatorIndexRoute: EstimatorIndexRoute,
}

const EstimatorRouteWithChildren = EstimatorRoute._addFileChildren(
  EstimatorRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  CommunityRoute: CommunityRoute,
  ContactRoute: ContactRoute,
  EstimatorRoute: EstimatorRouteWithChildren,
  GalleryRoute: GalleryRoute,
  KitchenRoute: KitchenRoute,
  LoginRoute: LoginRoute,
  RoofRoute: RoofRoute,
  ServicesRoute: ServicesRoute,
  TestimonialsRoute: TestimonialsRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
